### ISSUE TITLE
Path to models file

### ISSUE THREAD

**Issue by mbhall88** [rrwick/CNN-Demultiplexer#4]
Hi Ryan,

I think it might be a good idea to be a little clearer in your usage examples that the `--start_model` and `--end_model` arguments require the path to the models and just putting their names in such as in the example code snippets returns an error such as `Error: SQK-RBK004_read_starts does not exist`.

Following on from this, maybe it would be handy if you added in the ability for deepbinner to find the default models without the need for their path? Potentially you could have some shorter keywords for these such as `rapid` and `native`.

Thanks.

**Comment by LarsDu** [comment]
I second this!

**Comment by rrwick** [comment]
Thanks, that's a good suggestion. In the current (just pushed up to GitHub) version of Deepbinner, there are two new preset options: `--native` and `--rapid`. Using these should be equivalent to pointing Deepbinner directly to the model files.

Give a it try! I'll optimistically close this issue now, but let me know if anything's not working.

Ryan
