### ISSUE TITLE
support POD5 or SQK-RNA004 kit 

### ISSUE THREAD

**Issue by Seongmin-Jang-1165** [rrwick/CNN-Demultiplexer#44]
hello 

i produce multiplexed direct RNA seq data with SQK-RNA004 using target-specific custom adapter containing barcodes

do deepbinner supports POD5 data or SQK-RNA004 library??? also i want know it can analyze custom adapter

thank you

**Comment by rrwick** [comment]
Sorry, but Deepbinner is now deprecated, so it won't work with modern ONT data. That means it's almost certainly not the best tool to demultiplex your RNA reads, at least not without significant modification and training a new model 😢

Ryan
