### ISSUE TITLE
keras not installed

### ISSUE THREAD

**Issue by tolot27** [rrwick/CNN-Demultiplexer#7]
Im running Ubuntu 18.04 and the dependency `keras` is not installed during `python3 setup.py install`. I had to install it manually with `sudo -H pip3 install keras`.

I reported this because of the different information in the `README.md`.

**Comment by rrwick** [comment]
You are quite right - thanks for letting me know!

I had assuming `python3 setup.py install` would install the dependencies, but I now realise that doing so requires `pip`. (Still trying to wrap my head around the nuances of Python distribution.)

I've updated the README so I think the instructions are now correct.

Ryan
